### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by tkinsella** [ITRS-Group/monitor-ninja#12] opened 2017-12-20 17:05 UTC
When running make install I receive the following output:

`mkdir -m 0755 -p /usr/local/share/php
cp -a src/op5 /usr/local/share/php/op5
mkdir -m 770 -p /etc/op5
cp -R etc/* /etc/op5
chown -R apache:apache /etc/op5
mkdir -m 0755 -p 
mkdir: missing operand
Try 'mkdir --help' for more information.
make: *** [install-bin] Error 1
`

**Comment by LikoV2** [comment] 2017-12-23 20:48
Same issue here, I ran make install --debug, here is the input:

chown -R apache:apache /etc/op5
Successfully remade target file `install-config'.
File `install-bin' does not exist.
Must remake target `install-bin'.
Invoking recipe from Makefile:82 to update target `install-bin'.
mkdir -m 0755 -p 
mkdir: missing operand
Try 'mkdir --help' for more information.
make: *** [install-bin] Error 1

**Comment by LikoV2** [comment] 2018-01-09 22:38
Any update on this ? Is it linked to CentOS ?

**Comment by fmikker** [comment] 2018-01-16 13:36
Hi, I will have a look at this during the week. I'll get back to you.

**Comment by LikoV2** [comment] 2018-11-29 17:46
Hi,

Any update on this issue ? What is the best distribution for Naemon/Merlin/Ninja ? 

I tried installing Merlin on Debian 9, it was a headache.

**Comment by LikoV2** [comment] 2018-11-29 17:56
I may have found it, it fails on:

```
install-bin:
	mkdir -m 0755 -p $(BINDIR)
	cp install_scripts/op5-manage-users $(BINDIR)
```

I can't find where BINDIR is defined, that's why mkdir fails.

**Comment by LikoV2** [comment] 2018-11-30 14:07
Duplicate #8, you can close this one.

**Comment by jacobbaungard** [comment] 2019-05-14 07:21
Closing due to duplicate of #8

**Closed by jacobbaungard** 2019-05-14 07:21 UTC
Labels: bug, enhancement
